---
title: "Experience"
output:
  html_document:
    toc: true
    toc_float: true
---

### Education
Columbia University, MPH in Biostatistics, April 2021\
University of California, Davis, BS in Statistics, March 2019

### Courses
* Data Science I
* Applied Regression
* Applied Time Series Analysis
* Analysis of Categorical Data
* Applied Epidemiologic Analysis
* Design & Conduct of Observational Epidemiology
* Nonparametric Statistics and Statistical Data Science
* Relational Databases and SQL Programming for Research and Data Science

### Academic experience
Research on Detecting Vaccine Misinformation, UC Davis, 2018 - 2019\
Research on General Chemistry Lecture Capture Data, UC Davis, 2018 - 2019\
Research on Sensory and Consumer Science Research, UC Davis, 2018\
Research on Automated Monitoring of Water Stress in Plants, UC Davis, 2016\
Learning Assistant of General Chemistry Course, UC Davis, 2016

### Professional experience
PHIA Data Analytics Intern, ICAP at Columbia University, 2020\
Principal Data Analyst, Davis Sensory Institute, 2019

### Activities
CUMC CSSA Department of Networking, Columbia University, 2020\
Student Alumni Association (SAA) Director of Networking, UC Davis, 2018 - 2019\
Art & Lecture Committee Member, UC Davis, 2016 - 2019